# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0002_auto_20160319_2314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Narrrative',
            new_name='Narrative',
        ),
    ]
