# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='narrative',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 20, 21, 45, 18, 768396, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
